version: "3.9"

services:
  backend:
    build: .
    container_name: engenharia-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
